### ISSUE TITLE
overlay: Check if we can turn on config_wifi_background_scan_support

### ISSUE THREAD

**Issue by cryptomilk** [whatawurst/android_device_samsung_universal9820-common#19]
Check if we can turn on config_wifi_background_scan_support.

**Comment by Linux4** [comment]
Looks like we already have that turned on? https://github.com/whatawurst/android_device_samsung_exynos9820-common/blob/lineage-17.1/overlay/frameworks/base/core/res/res/values/config.xml#L87

**Comment by cryptomilk** [comment]
This works and has been fixed with cfcccd03aff9f1c64664b43ae8765a581b71aa66

Thanks @Linux-4
