### ISSUE TITLE
Need to contact you guys ASAP!

### ISSUE THREAD

**Issue by zunaid321** [whatawurst/android_device_samsung_universal9820-common#72]
Hey guys! Awesome work!

I have been requesting Ivan for the device tree for ages. But he keeps on saying soon.
I am a flashoholic. I literally try any GSIs out there. Keen on trying new roms and GSIs as well.

I am a S10+ user here.
I know more or less about android and all. If you need help to pull any files, do lemme know.

How can I contact you guys?
Did you make a telegram group or discord group?

I would love to join in the fun.

Do give me the contact details. Cheers!

Sorry for contacting you guys like this :P

**Comment by cryptomilk** [comment]
Write an email?

**Comment by zunaid321** [comment]
I am sorry 😅
Can I contact you guys in IRC?
Can you give me the instructions?

**Comment by cryptomilk** [comment]
I'm gladiac on Freenode.
